### ISSUE TITLE
Make The Camera Follow An Object

### ISSUE THREAD

**Issue by git900000** [dimitrisx/physion-assets#13]
This is not really an issue; it is actually an issue on the Physion website. I do not know how to make the camera follow an object.

**Comment by Carstyle476** [comment]
### It's **_not_** an issue on the Physion website, it actually is possible.
It's _very_ simple actually:
Step 1. Add a name to your object you want to follow
Step 2. Select the background, then the scene
Step 3. Scroll to "followed node"
Step 4. Click on it, and click on the name of your object
Alternatively, you can remember the ID of your object, and click on that when doing step 4
_Good to go!_ - when you press play, the camera will follow your object

**Comment by git900000** [comment]
Wow, thanks! Also, the note player is not working, even though I turned it on, and a note is set.

**Comment by Carstyle476** [comment]
You gotta set a note for the objects that hit the note player, not the note player itself

**Comment by git900000** [comment]
Thank you!
