### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by git900000** [dimitrisx/physion-assets#16]
Hello,
 
I would like for someone here to test out this (rewritten by AI) javascript file. It creates a ragdoll. Let me know if you encounter any issues and how I can fix them, and see if I can get this added to Physion. 

Sincerely,

-Git900000

**Comment by git900000** [comment]
P.S: It's fine if it takes too long to test it.

**Comment by git900000** [comment]
P.S.S: Also, it's because I don't know how to import it.

**Comment by dimitrisx** [comment]
What is this file? I cannot find any attached file

**Comment by git900000** [comment]
Oh, sorry.. I have it here...😅
[SimpleRagdoll.json](https://github.com/user-attachments/files/17076500/SimpleRagdoll.json)

**Comment by dimitrisx** [comment]
The placeholder textures that you're using do not exist and this result an empty (transparent) texture

Try changing to this:

        this._headUrl = "https://res.cloudinary.com/jeronimo/image/upload/v1726847612/Testing/smiley.png"; // Placeholder
        this._bodyUrl = "https://res.cloudinary.com/jeronimo/image/upload/v1726847612/Testing/smiley.png"; // Placeholder
        this._limbUrl = "https://res.cloudinary.com/jeronimo/image/upload/v1726847612/Testing/smiley.png"; // Placeholder


In order to test this script you need to

- Create a new Scene
- Paste your class in the browser's console and hit enter
- Enter the following code to instantiate it

var rg = new SimpleRagdoll();
rg.create(physion.root.scene);


P.S. Next time please use more  a descriptive title when creating an issue

**Comment by git900000** [comment]
What do you mean by the "browser's console"?

**Comment by dimitrisx** [comment]
Please google it

**Comment by git900000** [comment]
I googled it, and I actually can't use it because inspect is disabled :(

**Comment by git900000** [comment]
> I googled it, and I actually can't use it because inspect is disabled :(

This is because it requires inspect.

**Comment by git900000** [comment]
D'oh!

**Comment by git900000** [comment]
Oh, and one more thing. Do you know how I can download a scene from Physion and/or copy a specific section, then paste it into a different scene? If not, can you make this possible?
